build:
    environment:
        timezone: 'Europe/Zurich'
        php:
            version: '7.2'
            ini:
                'date.timezone': 'Europe/Zurich'
    nodes:
        postgres:
            services:
                postgres: 11
    tests:
        before:
            -
                command: PGPASSWORD=scrutinizer psql --host=127.0.0.1 --port=5432 --username=scrutinizer --command="CREATE USER root WITH ENCRYPTED PASSWORD 'root';"
            -
                command: PGPASSWORD=scrutinizer psql --host=127.0.0.1 --port=5432 --username=scrutinizer --command="ALTER USER root WITH SUPERUSER;"
            -
                command: composer self-update -q
            -
                command: composer global require hirak/prestissimo
        override:
            -
                command: 'vendor/bin/phpunit --testsuite=Unit --coverage-clover=coverage/clover.xml'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'php-clover'
            -
                command: 'vendor/bin/phpunit --testsuite=Integration'

checks:
    php: true

coding_style:
    php: {}

filter:
    excluded_paths:
        - 'tests/*'
