language: php

services:
  - postgresql

matrix:
  include:
    - php: 7.2
      env: dependencies=lowest
    - php: 7.2
      env: dependencies=highest
    - php: 7.3
      env: dependencies=lowest
    - php: 7.3
      env: dependencies=highest

before_script:
  - psql --username=postgres --command="CREATE USER root WITH ENCRYPTED PASSWORD 'root';"
  - psql --username=postgres --command="ALTER USER root WITH SUPERUSER;"
  - echo 'extension=apcu.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/apcu.ini
  - echo 'Europe/Zurich' | sudo tee /etc/timezone
  - echo 'date.timezone = "Europe/Zurich"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update -q
  - composer global require hirak/prestissimo
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;

script:
  - phpdbg -qrr vendor/bin/phpunit --testsuite=Unit --coverage-text --verbose
  - phpdbg -qrr vendor/bin/phpunit --testsuite=Integration --verbose
  - phpdbg -qrr vendor/bin/infection --threads=$(nproc) --min-msi=86 --verbose
  - vendor/bin/phpstan analyse
  - vendor/bin/phploc app --verbose
  - vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
  - if [ -z "$dependencies" ]; then vendor/bin/phpinsights analyse --no-interaction --min-quality=94; fi;
  - if [ "$dependencies" = "highest" ]; then vendor/bin/phpinsights analyse --no-interaction --min-quality=94; fi;
  - if [ "$dependencies" = "lowest" ]; then vendor/bin/phpinsights analyse --no-interaction --min-quality=94 --disable-security-check; fi;
