language: php

services:
  - postgresql

matrix:
  include:
    - php: 7.2
      env: dependencies=lowest
    - php: 7.2
      env: dependencies=highest
    - php: 7.3
      env: dependencies=lowest
    - php: 7.3
      env: dependencies=highest

before_script:
  - psql --username=postgres --command="CREATE USER root WITH ENCRYPTED PASSWORD 'root';"
  - psql --username=postgres --command="ALTER USER root WITH SUPERUSER;"
  - rm ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - echo 'extension=apcu.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/apcu.ini
  - echo 'Europe/Zurich' | sudo tee /etc/timezone
  - echo 'date.timezone = "Europe/Zurich"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update -q
  - composer global require hirak/prestissimo
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;

script:
  - composer test

after_success:
  - travis_retry composer test:coveralls
