version: '3.0'
services:
  php:
    container_name: petstore-php
    hostname: petstore-php
    build:
      dockerfile: ./dev/php/Dockerfile
      context: ./docker
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    environment:
      APP_ENV: dev
      DATABASE_USER: root
      DATABASE_PASS: root
      DATABASE_HOST: postgres
      DATABASE_NAME: petstore
      DATABASE_PORT: 5432
      SSH_AUTH_SOCK: /ssh-agent
      BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
      BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
    volumes:
      - ./:/var/www/html
      - ~/.bash_aliases:/var/www/.bash_aliases
      - ~/.bash_history:/var/www/.bash_history
      - ~/.gitconfig:/var/www/.gitconfig
      - $SSH_AUTH_SOCK:/ssh-agent
    depends_on:
      - postgres
  blackfire:
    image: blackfire/blackfire
    environment:
      BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
      BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
  postgres:
    container_name: petstore-postgres
    hostname: pestore-postgres
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  nginx:
    container_name: petstore-nginx
    hostname: petstore-nginx
    build:
      dockerfile: ./prod/nginx/Dockerfile
      context: ./docker
    ports:
      - "1337:443"
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
